version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  login_to_aws:
    docker: &docker_image
      - image: 'cimg/ruby:3.1.3-node'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION # this will use the env var
      - run: &ecr_login
          name: Login to ecr
          command: |
            aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
            aws configure export-credentials --format env
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  build_and_push_image:
    docker: &ecr_base_image
      - image: docker.io/ministryofjustice/fb-builder:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    working_directory: ~/circle/git/fb-maintenance-page
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: &workspace_envs
          command: |
            cat bash.env >> $BASH_ENV
      - setup_remote_docker: &remote_docker
          docker_layer_caching: true
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy_scripts/build'
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: main
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  deploy_to_services_test_dev:
    working_directory: ~/circle/git/fb-maintenance-page
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - run:
          name: deploy to test dev in EKS cluster
          environment:
            APPLICATION_NAME: fb-maintenance-page
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-services-test-dev
          command: './deploy_scripts/deploy_eks'
      - slack/status: *slack_status
  deploy_to_services_test_production:
    working_directory: ~/circle/git/fb-maintenance-page
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - run:
          name: deploy to test production in EKS cluster
          environment:
            APPLICATION_NAME: fb-maintenance-page
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-services-test-production
          command: './deploy_scripts/deploy_eks'
      - slack/status: *slack_status
  deploy_to_services_live_dev:
    working_directory: ~/circle/git/fb-maintenance-page
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - run:
          name: deploy to live dev (eks)
          environment:
            APPLICATION_NAME: fb-maintenance-page
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-services-live-dev
          command: './deploy_scripts/deploy_eks'
      - slack/status: *slack_status
  deploy_to_services_live_production:
    working_directory: ~/circle/git/fb-maintenance-page
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - run:
          name: deploy to live production (eks)
          environment:
            APPLICATION_NAME: fb-maintenance-page
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-services-live-production
          command: './deploy_scripts/deploy_eks'
      - slack/status: *slack_status

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - login_to_aws:
          context: &context
            - moj-forms
            - moj-forms-services-apps
      - build_and_push_image:
          context: *context
          requires:
            - login_to_aws
          filters:
            branches:
              only:
                - main
      - deploy_to_services_test_dev:
          context: *context
          requires:
            - build_and_push_image
      - deploy_to_services_test_production:
          context: *context
          requires:
            - build_and_push_image
      - deploy_to_services_live_dev:
          context: *context
          requires:
            - deploy_to_services_test_dev
            - deploy_to_services_test_production
      - deploy_to_services_live_production:
          context: *context
          requires:
            - deploy_to_services_test_dev
            - deploy_to_services_test_production
